WIP: dev-adrian01c welcome section
codetapacademy/my-cv-v2-starter pull request #88
Opened 2021-03-31 11:57 UTC by Adrian01C

2021-04-12 20:26 UTC, tandaraelena requested changes

2021-04-12 20:26 UTC, tandaraelena commented on web/index.html
> +      <button .class="disc">
Please delete the "." before the class word.

2021-04-12 20:26 UTC, tandaraelena commented on web/index.html
> +
Please delete this empty line

2021-04-12 20:29 UTC, tandaraelena requested changes

2021-04-12 20:29 UTC, tandaraelena commented on web/index.html
> +    <link rel="stylesheet" href="<link rel="preconnect" href="https://fonts.gstatic.com">
This line is confusing. I think you have an extra href attribute.

2021-04-13 03:38 UTC, psyhedeliq approved these changes
🚀 🚀 🚀

2021-04-13 06:41 UTC, simonamarcu2 approved these changes
good work

2021-04-13 07:10 UTC, RalucaRbc approved these changes

2021-04-14 06:53 UTC, tandaraelena approved these changes

2021-04-18 09:02 UTC, biggicode approved these changes
I approve it but you should change what Elena said

2021-04-18 09:13 UTC, ValentinaVanu approved these changes

2021-04-18 09:13 UTC, ValentinaVanu commented on web/css/style.css
> +  grid-template-columns: 1fr 1fr 1fr 1fr;
Can also be written as:
```suggestion
  grid-template-columns: repeat(4, 1fr);
```

2021-04-19 06:59 UTC, simonamarcu2 approved these changes
💯

2021-04-19 07:24 UTC, vasilemaftita approved these changes
Nice.

2021-04-19 07:25 UTC, vasilemaftita approved these changes

2021-04-19 07:34 UTC, Constantin-Matei approved these changes

2021-05-01 12:33 UTC, vasilemaftita approved these changes
Nice; Work.

2021-05-04 18:17 UTC, marianzburlea approved these changes

2021-05-04 18:18 UTC, merged